version: "3.7"

services:
  app:
    container_name: panabook-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    dns:
      - 4.4.4.4
      - 8.8.8.8
    ports:
      - "3001:3001"
