version: "3.7"

services:
  panabook-frontend:
    container_name: panabook-frontend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    dns:
      - 4.4.4.4
      - 8.8.8.8
    ports:
      - "3002:80"